version: '3'

networks:
    laravel:

services:
    nginx:
      build:
        args:
          user: laravel
          uid: 1000
          gid: 1000
        context: ./dockerfiles
        dockerfile: nginx.dockerfile
      container_name: nginx
      restart: unless-stopped
      ports:
        - "8088:80"
      volumes:
        - ./src:/var/www/app:delegated
      depends_on:
        - php
        - mysql
      networks:
        - laravel

    mysql:
      #image: mysql
      image: arm64v8/mysql:oracle #mysql image for mac m1 Silicon Valley support
      container_name: mysql
      restart: unless-stopped
      tty: true
      ports:
        - "3306:3306"
      volumes:
        - ./volumes/mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      networks:
        - laravel

    php:
      build:
        args:
          user: laravel
          uid: 1000
          gid: 1000
        context: ./dockerfiles
        dockerfile: php.dockerfile
      container_name: php
      volumes:
        - ./src:/var/www/app
      ports:
        - "9000:9000"
      environment:
        - "DB_HOST=mysql"
        - "DB_PORT=3306"
        - "DB_DATABASE=homestead"
        - "DB_USERNAME=homestead"
        - "DB_PASSWORD=secret"
      networks:
        - laravel