version: '3'

#Networks
networks:
  api_network:
    driver: bridge
  queue_network:
    driver: bridge

#Services
services:

  #Server
  nginx:
    build:
      args:
        user: laravel
        uid: 1000
        gid: 1000
      context: ./docker
      dockerfile: nginx.dockerfile
    restart: unless-stopped
    volumes:
      - ./src/api-gateway:/var/www/html:delegated
    depends_on:
      - api-gateway
      - mysql
    networks:
      - api_network

  #Database
  mysql:
    #image: mysql
    image: arm64v8/mysql:oracle #mysql image for mac m1 Silicon Valley support
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - api_network
#
#  #Redis Caching
#  redis:
#    build:
#      context: ./docker
#      dockerfile: redis.dockerfile
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./docker/volumes/redis:/data
#    networks:
#      - queue_network

  #APIGateway
  api-gateway:
    build:
      args:
        user: laravel
        uid: 1000
        gid: 1000
      context: ./docker
      dockerfile: php.dockerfile
    container_name: api-gateway
    volumes:
      - ./src/api-gateway:/var/www/html:delegated
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=secret"
    networks:
      - api_network

  #load balancer
  load-balancer:
    image: haproxy:latest
    links:
      - nginx
    depends_on:
      - nginx
    restart: always
    container_name: load-balancer
    volumes:
      - ./docker/configs/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8000:80"
    networks:
      - api_network